### ISSUE TITLE
Question about points  in preprocess/sfm_face_coordinates.npy

### ISSUE THREAD

**Issue by reyuri** [swook/faze_preprocess#4]
In preprocess/sfm_face_coordinates.npy, there are 14 3d points which i don't know their relations to face landmark points. To be specific ,if i want to get the 3d coordinates of the center of left eye(or right eye), which row it is in "face_model_3d_coordinates" array? Thanks for your great work , looking forward to your reply.

**Comment by swook** [comment]
Hullo. Sorry, I do not know how I missed this...

You can see in a new script that I just released for our NeurIPS paper, that we calculate the individual gaze for the left and right eyes (we do not use this actually).

The relevant lines of code are at: https://github.com/swook/faze_preprocess/blob/master/create_hdf_files_for_sted.py#L208

**Comment by ZhangLin-PKU** [comment]
Hi @swook , I want to know which facial landmarks the 14 3d points represent for. To be specific, I want to know the mapping from 14 points to [68 facial landmarks](https://ibug.doc.ic.ac.uk/resources/300-W/)/[98 facial landmarks](https://wywu.github.io/projects/LAB/WFLW.html). This is important to me because I want to train my own dataset, which is annotated with 68 facial landmarks.

Thank you for your work. I am looking forward to your reply.
